const state={verses:[],selected:new Set(),search:'',sort:'canonical'};
const refs={emotionList:document.getElementById('emotionList'),results:document.getElementById('results'),chips:document.getElementById('activeChips'),searchBox:document.getElementById('searchBox'),sortSelect:document.getElementById('sortSelect'),sectionTitle:document.getElementById('sectionTitle'),sectionSubtitle:document.getElementById('sectionSubtitle'),totalVerses:document.getElementById('totalVerses'),totalEmotions:document.getElementById('totalEmotions'),visibleCount:document.getElementById('visibleCount')};
async function loadData(){const response=await fetch('./gita-data.json');state.verses=await response.json();refs.totalVerses.textContent=state.verses.length;const emotions=getEmotionCounts();refs.totalEmotions.textContent=Object.keys(emotions).length;render();}
function getEmotionCounts(){const counts={};state.verses.forEach(v=>v.emotions.forEach(e=>counts[e]=(counts[e]||0)+1));return counts;}
function getSortedEmotions(){const counts=getEmotionCounts();return Object.keys(counts).sort((a,b)=>counts[b]-counts[a]||a.localeCompare(b)).map(name=>({name,count:counts[name]}));}
function filterVerses(){let data=[...state.verses];if(state.selected.size)data=data.filter(v=>v.emotions.some(e=>state.selected.has(e)));const q=state.search.trim().toLowerCase();if(q)data=data.filter(v=>[v.ref,v.key,v.sanskrit,v.english,v.emotions.join(' ')].join(' ').toLowerCase().includes(q));if(state.sort==='emotion')data.sort((a,b)=>a.emotions[0].localeCompare(b.emotions[0])||a.chapter-b.chapter||a.verse-b.verse);else if(state.sort==='chapter')data.sort((a,b)=>a.chapter-b.chapter||a.verse-b.verse);return data;}
function renderEmotions(){refs.emotionList.innerHTML=getSortedEmotions().map(({name,count})=>`<button class="emotion-btn ${state.selected.has(name)?'active':''}" data-emotion="${name}" aria-pressed="${state.selected.has(name)}"><span>${name}</span><small>${count}</small></button>`).join('');refs.emotionList.querySelectorAll('[data-emotion]').forEach(btn=>btn.addEventListener('click',()=>{const emotion=btn.dataset.emotion;state.selected.has(emotion)?state.selected.delete(emotion):state.selected.add(emotion);render();}));}
function renderChips(){refs.chips.innerHTML=[...state.selected].map(em=>`<button class="chip" data-remove="${em}">${em} ✕</button>`).join('');refs.chips.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{state.selected.delete(btn.dataset.remove);render();}));}
function renderResults(){const data=filterVerses();refs.visibleCount.textContent=data.length;refs.sectionTitle.textContent=state.selected.size?[...state.selected].join(', '):'All verses';refs.sectionSubtitle.textContent=state.search?`Search results for “${state.search}”.`:'Browse the emotion-tagged verse collection.';if(!data.length){refs.results.innerHTML='<div class="empty">No verses matched this filter. Try a different emotion or broader search term.</div>';return;}refs.results.innerHTML=data.map(v=>`<article class="surface verse-card"><div class="verse-meta"><div><div class="verse-ref">${v.ref}</div><div class="emotion-tags">${v.emotions.join(' · ')}</div></div><span class="badge">${v.key}</span></div><div class="sanskrit">${v.sanskrit}</div><div class="english">${v.english}</div></article>`).join('');}
function render(){renderEmotions();renderChips();renderResults();}
refs.searchBox.addEventListener('input',e=>{state.search=e.target.value;renderResults();});refs.sortSelect.addEventListener('change',e=>{state.sort=e.target.value;renderResults();});
(function(){const t=document.querySelector('[data-theme-toggle]');const r=document.documentElement;let d=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';r.setAttribute('data-theme',d);t.textContent=d==='dark'?'☀️':'🌙';t.addEventListener('click',()=>{d=d==='dark'?'light':'dark';r.setAttribute('data-theme',d);t.textContent=d==='dark'?'☀️':'🌙';t.setAttribute('aria-label','Switch to '+(d==='dark'?'light':'dark')+' mode');});})();
document.getElementById('downloadJson').addEventListener('click',()=>{fetch('./gita-data.json').then(r=>r.blob()).then(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gita-data.json';a.click();URL.revokeObjectURL(a.href);});});
loadData();
